---
# playbook.yml
- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: "build the docker image of myname from the mightly alpine"
      become: true
      docker_image:
        name: "myname"
        path: "../project-myname"
